<a href="https://colab.research.google.com/github/poojitha-unnam/pns_2303A51304/blob/main/LAB_01_PNS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Import Numpy Library

In [20]:
import numpy as np

In [21]:
A=np.array([[9,10,11],[15,16,17],[21,22,23],[35,36,37]])
print(A)

[[ 9 10 11]
 [15 16 17]
 [21 22 23]
 [35 36 37]]


In [22]:
print(A[0,:])
print(A[1,:])
print(A[2,:])
print(A[3,:])

[ 9 10 11]
[15 16 17]
[21 22 23]
[35 36 37]


In [23]:
print(A[:,2])

[11 17 23 37]


In [24]:
print(A[2,:])

[21 22 23]


In [25]:
print(np.size(A))

12


In [26]:
print(A[2,2])

23
